           
CREATE OR REPLACE PROCEDURE PROCEDURE_INSERT (
V_1 VARCHAR2,
V_2 DATE,
V_3 VARCHAR
) AS
BEGIN
    INSERT INTO TABELA_PROCEDURES VALUES (
        SQ_PROCEDURE.NEXTVAL,
        V_1,
        V_2,
        V_3
    );
    
    COMMIT;

END;