SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE PROC2 IS V_VALOR NUMBER;
BEGIN
    V_VALOR := FUN_CALCULA_FGTS(5000);
    DBMS_OUTPUT.PUT_LINE('O VALOR DO FGTS É: ' || TO_CHAR(V_VALOR));
END PROC2;    


EXEC PROC2();



