----- CODIGO COM CURSOR EXPLÍCITO
DECLARE 
V_CODIGO PRODUTO.COD_PRODUTO%TYPE := 5;
CURSOR CUR_EMP IS
    SELECT NOM_PRODUTO FROM PRODUTO WHERE   COD_PRODUTO = V_CODIGO;
BEGIN   
    FOR X IN CUR_EMP LOOP
        INSERT INTO HISTORICO VALUES ( X.NOM_PRODUTO, SYSDATE);
        COMMIT;
    END LOOP;
END;   

----- CODIGO COM CURSOR IMPLICITO
SET SERVEROUTPUT ON;

DECLARE
V_NOME CLIENTE.NOM_CLIENTE%TYPE;
BEGIN
    FOR X IN (SELECT NOM_CLIENTE FROM CLIENTE WHERE COD_CLIENTE = 1) LOOP
         INSERT INTO HISTORICO VALUES (V_NOME, SYSDATE);
         COMMIT;
    END LOOP;
END;


