--- EXERCICIO 1
DECLARE
CURSOR C_CONSULTA_CLIENTE IS
    SELECT COD_CLIENTE, NOM_CLIENTE FROM CLIENTE;
BEGIN
    FOR X IN C_CONSULTA_CLIENTE LOOP
    DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || X.COD_CLIENTE || CHR(10) ||
                         'NOME: ' || X.NOM_CLIENTE);
    END LOOP;
END;    


--- EXERCICIO 2
CREATE OR REPLACE PROCEDURE PRC_VALIDA_TOTAL_PEDIDO(VCOD_PEDIDO PEDIDO.COD_PEDIDO%TYPE) IS

FINAL_VALUE NUMBER :=0;
P_RETORNO VARCHAR2(30):= 'PEDIDO OK';
CURSOR FIND_ITEM IS
    SELECT COD_PEDIDO, VAL_TOTAL_PEDIDO FROM PEDIDO WHERE COD_PEDIDO = VCOD_PEDIDO;
CURSOR SUM_TOTAL_ITEMS(P_RETORNO VARCHAR2) IS
    SELECT QTD_ITEM, VAL_UNITARIO_ITEM, VAL_DESCONTO_ITEM FROM ITEM_PEDIDO WHERE COD_PEDIDO = VCOD_PEDIDO;
BEGIN
    FOR X IN FIND_ITEM LOOP
        FOR Y IN SUM_TOTAL_ITEMS(P_RETORNO) LOOP
            FINAL_VALUE := (Y.QTD_ITEM * Y.VAL_UNITARIO_ITEM) - Y.VAL_DESCONTO_ITEM;
        END LOOP;
            IF FINAL_VALUE = X.VAL_TOTAL_PEDIDO THEN
                DBMS_OUTPUT.PUT_LINE(P_RETORNO);
            ELSE
                P_RETORNO := 'PEDIDO INVÁLIDO';
                DBMS_OUTPUT.PUT_LINE(P_RETORNO);
            END IF;
    END LOOP;
END;    

CALL PRC_VALIDA_TOTAL_PEDIDO(1002);
        
        