---3. Crie um procedure para atualizar a quantidade de produtos e estoque.
CREATE OR REPLACE PROCEDURE ATT_PRODUTO(
VCOD_PRODUTO ESTOQUE_PRODUTO.COD_PRODUTO%TYPE,
VQTD_PRODUTO ESTOQUE_PRODUTO.QTD_PRODUTO%TYPE
) IS 
BEGIN

    UPDATE ESTOQUE_PRODUTO
    SET QTD_PRODUTO = VQTD_PRODUTO
    WHERE COD_PRODUTO = VCOD_PRODUTO;
    
        
END ATT_PRODUTO;