--4. Crie uma procedure para deletar um pedido.

CREATE OR REPLACE PROCEDURE DELETAR_PEDIDO(VCOD_PEDIDO PEDIDO.COD_PEDIDO%TYPE)IS
BEGIN
    DELETE FROM PEDIDO
    WHERE COD_PEDIDO = VCOD_PEDIDO;
END DELETAR_PEDIDO;